
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    dao:
      - link:            "mysql:root:12345678@tcp(127.0.0.1:3306)/oldme"
        descriptionTag:  true
        noModelComment:  true

  build:
    name: "github.com/oldme-git/oldme-api"
    arch: "amd64"
    system: "linux"
